### ISSUE TITLE
Roadmap for V1

### ISSUE THREAD

**Issue by CDLemmi** [CDLemmi/basic-button-engine#1]
- [x] recognize click position (and send event)
- [x] draw rectangle as button
- [x] map position to button 
- [x] print specific text for each button to console for each click
